apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: snimmo-keycloak
  labels:
    app: sso
spec:
  externalAccess:
    enabled: true
    tlsTermination: reencrypt
    host: PATCH
  instances: 1